### ISSUE TITLE
Should apt-get update failures be fatal?

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/devops#10]
Occasionally, the ubuntu apt index is unavailable as they release an update.  This causes updating the apt package index operation to fail, causing the apt-get update operation to return -1, which in turn bails on the `deploy-mgmt-hub.sh` script.  Should this cause the script to fail, or should it be allowed to continue if the operator is notified and approves of continuing?

```
root@ubun2:~# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
----------- Verifying input and the host OS...
Manaagement hub services will listen on 127.0.0.1
Updating apt package index...
Error running apt-get update -q: Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Reading package lists...
E: Release file for http://us.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1h 41min 20s). Updates for this repository will not be applied.
E: Release file for http://us.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 1h 42min 54s). Updates for this repository will not be applied.
E: Release file for http://us.archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 1h 40min 7s). Updates for this repository will not be applied.
```

**Comment by bmpotter** [comment]
If the `apt-get update` fails, isn't it likely the subsequent `apt-get install` commands will fail too? Even if they don't, the script results in installing a significant number of packages. Having the exact results of that be indeterminate because the repo list isn't fully up to date seems bad.

Also, i avoid prompting because it makes it difficult to call this script from higher level scripts.

**Comment by joewxboy** [comment]
Probably a valid concern.  We should note this and close.
