### ISSUE TITLE
Object to note Open Horizon component version compatibility per release 

### ISSUE THREAD

**Issue by t-fine** [open-horizon/devops#103]
It was brought up in the Examples Working Group that it would be nice to have an easy to reference object that noted the compatible versions of all the Open Horizon components when a new "release" is created.

**Comment by bencourliss** [comment]
The Examples releases will now have a text file named `openhorizon-tested-versions.txt` that will contain the list of images that have been tested and are released and available on Dockerhub. See https://github.com/open-horizon/examples/releases/download/v2.30.0-947/openhorizon-tested-versions.txt for an example.
