### ISSUE TITLE
GHA needed to copy Mgmt-Hub documentation to OH Docs

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/devops#106]
There is a good set of documentation in the devops/mgmt-hub repo about how to set up the All-in-one Horizon Management Hub, Agent, and CLI

It does not appear in the Open Horizon documentation however.

Add a Copy Docs GHA and configure it to copy the mgmt-hub folder README content to open-horizon.github.io/docs/mgmt-hub

**Comment by johnwalicki** [comment]
Now that the GHA for anax/docs is implemented, let's stay on roll and also set up a GHA for devops/docs to docs/devops
https://github.com/open-horizon/anax/issues/3044

**Comment by johnwalicki** [comment]
@Sukriti-sood - we need a similar GHA for devops/docs

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood - we need a similar GHA for devops/docs

yup, will implement it

**Comment by johnwalicki** [comment]
Did #110 make the GHA work?

**Comment by johnwalicki** [comment]
The GHA to copy
```
        src_path: mgmt-hub/README.md
        dst_path: /docs/mgmt-hub/index.md
```
is failing.  The error is :
```
 Copying "devops/mgmt-hub/README.md" and pushing it to open-horizon/open-horizon.github.io
Cloning into '***@github.com/open-horizon/devops.git'...
fatal: unable to access 'https://***/': Could not resolve host: ***
Cloning 'open-horizon/devops' failed
```

**Comment by johnwalicki** [comment]
1. Do we need to create the `docs/devops` directory in the open-horizon.github.io repo first?
2. I compared 
```
https://raw.githubusercontent.com/open-horizon/devops/master/.github/workflows/copy-docs.yml
https://raw.githubusercontent.com/open-horizon/anax/master/.github/workflows/copydocs.yml
```
and see several differences.

**Comment by Sukriti-sood** [comment]
@johnwalicki Please confirm that you have filled out the `PERSONAL_TOKEN` secret with `Personal Access Token` Value. The directory structure is correct, I tested the same workflow in my own repository.

**Comment by johnwalicki** [comment]
I think so... https://github.com/open-horizon/devops/actions/runs/2205341529/workflow
```
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
```
is set to https://github.com/open-horizon/devops/settings/secrets/actions
Repository secrets
PERSONAL_TOKEN

**Comment by johnwalicki** [comment]
To be honest, I made up a PERSONAL_TOKEN secret with a splat of characters. Didn't put it anywhere else.

**Comment by Sukriti-sood** [comment]
Hi @johnwalicki , Can we have google meet when you are available. This will better help me to understand the context.

**Comment by joewxboy** [comment]
@johnwalicki At this point, I suspecct (with no concrete evidence) that the paths are causing the URL generation to fail because they are not folders:

        src_path: mgmt-hub/README.md
        dst_path: /docs/mgmt-hub/index.md

Maybe change it to this:

        src_path: mgmt-hub
        dst_path: /docs/mgmt-hub

**Comment by naphelps** [comment]
Completed.
