### ISSUE TITLE
Enable HTTPS for all-in-1

### ISSUE THREAD

**Issue by JoergWende** [open-horizon/devops#11]
### Mini-design:

- TLS only supported on linux (not macos)
- Change http: to ${HZN_TRANSPORT}:
- if HZN_TRANSPORT==https create key/cert in `/etc/horizon/keys/horizonMgmtHub.{crt,key}` (if doesn't exist yet):
    ```
        openssl req -newkey rsa:4096 -nodes -sha256 -x509 -keyout $CERT_DIR/$CERT_BASE_NAME.key -days 365 -out $CERT_DIR/$CERT_BASE_NAME.crt -subj "/C=US/ST=NY/L=New York/O=allin1@openhorizon.org/CN=$(hostname)" -extensions san -config <(echo '[req]'; echo 'distinguished_name=req'; echo '[san]'; echo "subjectAltName=IP:$allIPs")
    ```
    - `ln -sf horizonMgmtHub.crt sdoapi.crt && ln -sf horizonMgmtHub.key sdoapi.key`   #todo: add to sdo env vars for the key paths
    - `ln -s /etc/horizon/keys/horizonMgmtHub.crt /etc/ssl/certs` ??
- if HZN_TRANSPORT==http remove the keys/certs (so mounts in docker-compose.yml will mount empty dir)
- Have purge delete the key/cert
- Set `HZN_MGMT_HUB_CERT_PATH=$CERT_DIR/$CERT_BASE_NAME.crt` in `/etc/default/horizon` and `agent-install.cfg`
- Add cert as `agent-install.crt` to CSS
- At end of script, output `export HZN_MGMT_HUB_CERT_PATH=$CERT_DIR/$CERT_BASE_NAME.crt`
- Agbot:
    - Set in agbot-tmpl.json:
    ```
        "SecureAPIServerCert": "/home/agbotuser/keys/horizonMgmtHub.crt",
        "SecureAPIServerKey": "/home/agbotuser/keys/horizonMgmtHub.key",
    ```
    - Mount /etc/horizon/keys to /home/agbotuser/keys
- SDO:
    - Mount /etc/horizon/keys to /home/sdouser/ocs-api-dir/keys
- CSS:
    - Set in css-tmpl.conf:
    ```
        ListeningType secure
        SecureListeningPort 8080
        ServerCertificate /home/cssuser/keys/horizonMgmtHub.crt
        ServerKey /home/cssuser/keys/horizonMgmtHub.key
    ```
    - Mount /etc/horizon/keys to /home/cssuser/keys
- (wait until it supports TLS) Exchange:
    - change other container's references to exchange
- Postgres & Mongo:
    - Neither of these expose any ports on the host, so don't need to TLS them at this point

### Original request from @JoergWende :

Hi,

I've tried to set https as the communication protocol but the CSS container does not start with:
Invalid communication protocol, please choose either HTTP or MQTT or WIoTP

Before digging any deeper - is there a standard way to run a secure infrastructure ?

Cheers
J.

**Comment by dabooz** [comment]
@JoergWende In the anax repo, the builtin test environment runs the CSS with HTTPS enabled, so it is possible. In the CSS config file you have to set "ListeningType secure", "SecureListeningPort 9443" - doesnt have to be port 9443, "ServerCertificate /certs/css.crt" - whatever cert you generate, "ServerKey /certs/css.key" - whatever private key you have for the cert. And you can leave "CommunicationProtocol http", do not change it to https.

The script that starts the mgmt hub in this repo has SSL turned off to make the environment simpler.

**Comment by bmpotter** [comment]
@JoergWende also, be aware that the exchange doesn't currently support https natively (w/o a front-end ingress terminating the TLS). And as dave said, the `deploy-mgmt-hub.sh` script is intended for dev/test, which is why it sets up only http. If you can add https to it w/o making it more complicated for developers that don't need that, I'm open to a PR.

**Comment by bmpotter** [comment]
Both the exchange and sdo mgmt hub components are currently adding https support, so i'm planning to implement this issue in the next couple of weeks.

**Comment by bmpotter** [comment]
Waiting for https://github.com/open-horizon/exchange-api/pull/500 to be merged, so i can modify all-in-1 to also configure the exchange for TLS

**Comment by bmpotter** [comment]
Added TLS support for exchange.

All-in-1 TLS has been tested by several users, include e2edev.
