### ISSUE TITLE
The documentation directory is not showing up!

### ISSUE THREAD

**Issue by Al-tekreeti** [open-horizon/devops#112]
Did I do something wrong? The merged changes are not there!

_Originally posted by @Al-tekreeti in https://github.com/open-horizon/devops/issues/75#issuecomment-1148587250_

**Comment by joewxboy** [comment]
This repo is not following the documentation conventions and placing the README and other markdown files in a `/docs` folder.  This convention is what integrates the documentation.  Create a `/docs` folder and place the markdown docs into it in order to fix.

**Comment by joewxboy** [comment]
See issue #99

**Comment by johnwalicki** [comment]
Fixed by #99
