### ISSUE TITLE
Broken link in README.md mgmt-hub/README.md

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/devops#128]
Links in [devops/README.md](https://github.com/open-horizon/devops/blob/master/README.md) and [devops/mgmt-hub/README.md](https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md)

are pointed to https://open-horizon.github.io/docs/devops/ which give an error

```
Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. [Go back to Homepage.](https://open-horizon.github.io/)
```

**Comment by marhabac33** [comment]
@joewxboy can I work on this issue?

**Comment by joewxboy** [comment]
Thanks, @marhabac33 and let me know if you have any questions.
