### ISSUE TITLE
Hyperlink format is incorrect on All-in-One doc

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/devops#130]
Hyperlink format is HTML therefore it shows up as plain text instead of hyperlink on https://open-horizon.github.io/docs/mgmt-hub/docs/index.html

Note: https://github.com/open-horizon/open-horizon.github.io/pull/339 was delivered to fix the format over in https://github.com/open-horizon/open-horizon.github.io/ . However the approach is wrong because GH action will overwrite the fix next time the page is updated in the [devops](https://github.com/open-horizon/devops/) repo

![image](https://user-images.githubusercontent.com/8888996/195737450-4614b140-4ba8-4011-9923-fe10d88a5b66.png)

**Comment by marhabac33** [comment]
@johnwalicki please assign me the issue. I will have the PR up.

**Comment by johnwalicki** [comment]
Thanks @marhabac33
