### ISSUE TITLE
Fix Mgmt Hub redirect link

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/devops#132]
The https://github.com/open-horizon/devops/blob/master/README.md points to a dead link.
It should point to
https://open-horizon.github.io/docs/mgmt-hub/docs/index.html

**Comment by jsvigneshkanna** [comment]
Please to my name, will fix it

**Comment by johnwalicki** [comment]
Actually it was reported in #128  by @marhabac33 but I had not merged the PR yet.  Fixed in #129 

That's why I was having deja vu.
