### ISSUE TITLE
Install script in readme not working

### ISSUE THREAD

**Issue by rvandiessen** [open-horizon/devops#16]
Downloading the Horizon agent and CLI packages...
Error: http code 404 from: downloading https://github.com/open-horizon/anax/releases/latest/download/ubuntu.bionic.amd64.assets.tar.gz, stdout: Not Found

I used the readme:
https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md

**Comment by bmpotter** [comment]
Yes, the naming convention for anax releases changed. Fixed by https://github.com/open-horizon/devops/pull/17 which has been merged.

Please comment on this issue, if it is working for you now.

**Comment by rvandiessen** [comment]
Just did a new install and everything worked.
Thanks for the quick response!
