### ISSUE TITLE
mgmt-hub: agbot-tmpl.json contains an invalid JSON document

### ISSUE THREAD

**Issue by loudonlune** [open-horizon/devops#186]
The [agbot configuration template](https://github.com/open-horizon/devops/blob/master/mgmt-hub/agbot-tmpl.json) appears to have an error message in the first line, making it an invalid JSON document after being templated with envsubst. This breaks the agbot container when the management hub is installed, and could break the agbot container when a deployment is updated or otherwise changed by the all-in-one script.

Steps to reproduce:
1. Install the management hub on a system using the all-in-one installer script.
2. Observe that the management hub fails to install due to not being able to reach the exchange.
3. Observe that, in the output of `docker logs agbot`, the service is panicking and restarting due to invalid characters in its configuration file.

**Comment by joewxboy** [comment]
@naphelps it looks like you committed this file: https://github.com/open-horizon/devops/blob/548a1dbe6cf864ee461569eebe04a12bb4071dd2/mgmt-hub/agbot-tmpl.json

**Comment by naphelps** [comment]
Fixed in master and new-mongodb.
