### ISSUE TITLE
macOS Installation Prerequisites

### ISSUE THREAD

**Issue by clementkng** [open-horizon/devops#21]
In the [All-in-1 readme](https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md), the instructions mention that this should be able to run in Mac. However, after running `sudo -i` and then `curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash` I get this result.

```
----------- Verifying input and the host OS...
Management hub services will listen on 127.0.0.1
Installing prerequisites using brew, this could take a minute...
Error running brew install jq gettext: Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

A workaround is to brew install all the necessary packages before running `sudo -i`. I exited `sudo -i`, ran `brew install jq gettext`, entered sudo again, and the install went further before I encountered this message.
```
Configuring the Horizon agent and CLI...
Starting the Horizon agent container...
You must have socat installed to run this command.
Install socat using homebrew: http://macappstore.org/socat/, or using MacPorts: https://www.macports.org/ then 'sudo port install socat'
Error: exit code 2 from: starting agent
```

After exiting from `sudo -i` and running `brew install socat`, I was able to run `sudo -i` once more and then was able to successfully install the All-in-1.

Ideally, I think the script should be refactored to somehow get around that limitation. A shorter term solution is to update the instructions to pre-install the packages I listed above. I understand that this might be low priority since the Mac instructions are considered experimental, but I'm willing to try taking this on to ensure others have a smoother experience getting set up with Open Horizon 😃 

If it helps, I'm running macOS Catalina Version 10.15.5.

**Comment by bmpotter** [comment]
@clementkng Thx for reminding me that brew shouldn't be run as root. I took your advice on the short term solution and updated the readme to specify that on macos they need to install jq, gettext, and socat before running the script.

I'm interested in what solution you suggest for the longer term to automatically handle the prereqs in `deploy-mgmt-hub.sh`. As far as i know there is no way to have script downgrade its effective id to the user before `sudo -i` was run. I guess another approach is to not have them run the script with sudo, and then have the script put sudo in front each cmd that needs it, but that is kind of messy and error prone. What are your thoughts?

**Comment by clementkng** [comment]
@bmpotter Yeah, I can't think of or find any other way other than the two ways you mentioned. Even looking at the script, I can't really tell where sudo would need to be applied so maybe it's best to leave the script as it is now (one extra command for Mac users isn't too much).

**Comment by bmpotter** [comment]
@clementkng Ok, then i'll close this issue as complete (i made the readme updates). If you come up with a better way to handle this, you can reopen the issue.
