### ISSUE TITLE
what's the password means 

### ISSUE THREAD

**Issue by xauthulei** [open-horizon/devops#23]
I have installed a local all in one env, `what 's password means`?  or where to use it 

hzn exchange user list -v
[verbose] Reading configuration file: /usr/local/etc/horizon/hzn.json
[verbose] Reading configuration file: /etc/default/horizon
[verbose] Config file does not exist: /var/root/.hzn/hzn.json.
[verbose] No project level configuration file found.
[verbose] The exchange url: http://host.docker.internal:3090/v1
[verbose] GET http://host.docker.internal:3090/v1/orgs/myorg/users/admin
[verbose] HTTP request timeout set to 30 seconds
[verbose] HTTP code: 200
{
  "myorg/admin": {
    "admin": true,
    "email": "not@used",
    "hubAdmin": false,
    "lastUpdated": "2020-11-30T08:07:14.655237Z[UTC]",
    "password": "********",
    "updatedBy": "root/root"
  }
}

**Comment by bmpotter** [comment]
The password is the password for the `admin` user in the `myorg` organization. It is displayed in the last 2 lines of output from the `deploy-mgmt-hub.sh` script:

```
export HZN_ORG_ID=myorg
export HZN_EXCHANGE_USER_AUTH=admin:<pw>
```

Where `<pw>` is replaced by the actual password. The only place you have to use that password is in the `HZN_EXCHANGE_USER_AUTH` environment variable, as shown above. The `hzn exchange ...` commands use the `HZN_EXCHANGE_USER_AUTH` environment variable as credentials.

When you list the user with `hzn exchange user list` it intentionally obscures the password with `********` .

If this answers your question, please comment and close this issue.

**Comment by xauthulei** [comment]
@bmpotter  Got it, Thanks for your clear info. Meanwhile,   why it is a hide string `*********` or how to get its real value if I needed it.

**Comment by bmpotter** [comment]
@xauthulei you can't query the password, that would be a serious security exposure. In fact the horizon exchange doesn't even know the password, because as soon as it gets it, it 1-way encrypts, so the only thing it is able to do is check if a clear password it is given is correct. This is standard practice, and the reason the `deploy-mgmt-hub.sh` outputs this instruction at the end:

```
Important: save these generated passwords/tokens in a safe place. You will not be able to query them from Horizon.
```

**Comment by xauthulei** [comment]
@bmpotter , well. Thanks
