### ISSUE TITLE
How to uninstall open horizon

### ISSUE THREAD

**Issue by tinkoosingh** [open-horizon/devops#27]
I installed open horizon, it was working fine but I forgot to save HZN_ORG_ID and HZN_EXCHANGE_USER_AUTH. Then I restarted my system, after restart I was unable to make connection with horizon api (getting error). I tried reinstalling it but I was getting same error in re-installation.

Error: Can't connect to the Horizon REST API to run GET http://localhost:8510/node. Run 'systemctl status horizon' to check if the Horizon agent is running. Or set HORIZON_URL to connect to another local port that is connected to a remote Horizon agent via a ssh tunnel. Specific error is: Get "http://localhost:8510/node": dial tcp 127.0.0.1:8510: connect: connection refused

Output of command "systemctl status horizon":

horizon.service - Service for Horizon control system
   Loaded: loaded (/lib/systemd/system/horizon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-01-15 00:45:54 IST; 15min ago
  Process: 23471 ExecStart=/usr/horizon/bin/anax -v $ANAX_LOG_LEVEL -logtostderr -config /etc/horizon/anax.json (code=exited, status=98)
 Main PID: 23471 (code=exited, status=98)

Jan 15 00:45:54 user-Vostro-3546 systemd[1]: horizon.service: Service hold-off time over, scheduling restart.
Jan 15 00:45:54 user-Vostro-3546 systemd[1]: horizon.service: Scheduled restart job, restart counter is at 6.
Jan 15 00:45:54 user-Vostro-3546 systemd[1]: Stopped Service for Horizon control system.
Jan 15 00:45:54 user-Vostro-3546 systemd[1]: horizon.service: Start request repeated too quickly.
Jan 15 00:45:54 user-Vostro-3546 systemd[1]: horizon.service: Failed with result 'exit-code'.
Jan 15 00:45:54 user-Vostro-3546 systemd[1]: Failed to start Service for Horizon control system.

**Comment by tinkoosingh** [comment]
I would love to work on this issue. Please assign it to me.

**Comment by Prithvipal** [comment]
Please assign this issue to me as well.

**Comment by codejaeger** [comment]
@tinkoosingh I could get around this by removing the packages horizon and horizon-cli completely i.e.
`apt-get remove horizon horizon-cli`
Then simply re-run the script. There is also a flag -P (when used with -S that solves the issue) but it also deletes the created volumes for the containers.
Did you find a better alternative?

**Comment by tinkoosingh** [comment]
Uninstall feature was already there in existing script, only image deletion logic was missing. So fixed as part of pr https://github.com/open-horizon/devops/pull/42.

Hence closing this issue.
