### ISSUE TITLE
Add multi-tenancy support to deploy-mgmt-hub.sh

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/devops#32]
- [x] Have the script automatically add a hub admin using a curl command similar to:
```
curl -sS -w %{http_code} -u "root/root:${EXCHANGE_ROOT_PW:?}" -X POST -H Content-Type:application/json -d '{"hubAdmin":true,"admin":false,"password":"abc","email":""}' $HZN_EXCHANGE_URL/orgs/root/users/hubadmin | jq
```
- [x] Manually test that `hubadmin` can create an org using `hzn exchange org create ...`
- [x] Add example of adding an org in the "What's Next" section of documentation

**Comment by diru1100** [comment]
Hey @bmpotter, are you working on this issue?

I am new to OH and trying to understand different repos, it would be great if I can work on this issue.

**Comment by bmpotter** [comment]
Dandamudi,
 
Yes, you can work on it. You need to first post a comment to the issue asking to work on it, so github will let me assign it to you
 
Bruce Potter STSM, IBM Edge Computing, IBM, NYEmail: bp@us.ibm.com
 
 
----- Original message -----From: Dandamudi Rohit <notifications@github.com>To: open-horizon/devops <devops@noreply.github.com>Cc: bmpotter <bp@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [open-horizon/devops] Add multi-tenancy support to deploy-mgmt-hub.sh (#32)Date: Wed, Feb 3, 2021 11:23 PM 
 
Hey @bmpotter, are you working on this issue?
I am new to OH and trying to understand different repos, it would be great if I can work on this issue.

**Comment by diru1100** [comment]
Yes @bmpotter 

I have deleted the comment as I was already assigned 2 issues when I commented, and didn't want to overburden myself with more.

Have made PRs for them both and am glad to work on this as well.

Thank you for getting back to me.

**Comment by bmpotter** [comment]
Implemented in https://github.com/open-horizon/devops/pull/52

**Comment by bmpotter** [comment]
Tested by multiple people over the last 4 months.
