### ISSUE TITLE
More deployment flexibility

### ISSUE THREAD

**Issue by andreas-ibm** [open-horizon/devops#38]
I love the all-in-one script, but I want to take it further!

I've already made a cut-down version of the script (`deploy-node.sh`) to just install an agent and at some point in the future will want a `deploy-cluster.sh` too.

Plus flags to not actually run anything on the node.

Would this group be interested in such scripts, and would it be preferable to have them in a single script (a generic `deploy.sh` with lots of flags) or multiple?

cheers,
Andreas

**Comment by mounaiban** [comment]
> ...to just install an agent...

> Plus flags to not actually run anything on the node.

Yes, please make this happen. Especially that "do nothing" mode. Dry runs are a lifesaver to testers.

I'm voting to have a single script that does both agent-only and agent-with-hub installations. But if you end up going for multiple scripts, then I would prefer a hub-only script and an agent-only script.

**Comment by andreas-ibm** [comment]
@bmpotter any comment?

**Comment by andreas-ibm** [comment]
I'm also wondering whether I should make the `deploy-mgmt-node.sh` output a shell-script too with the appropriate variables, like spitting out a `hzn-admin.sh` and a `hzn-user.sh` for users to source before running `hzn` commands and the `deploy-node.sh` script (or `deploy.sh -n` if a more generic script is desired)

**Comment by andreas-ibm** [comment]
What's the relationship with https://github.com/open-horizon/anax/releases/latest/download/agent-install.sh? I see it's referenced in `deploy-mgmt-node.sh` but not actually used. It seems to support both edge and cluster nodes so could fit a lot of my needs...

**Comment by andreas-ibm** [comment]
sorry @mounaiban but the `agent-install.sh` script from the anax repo does everything I need! Going to close this issue.

**Comment by mounaiban** [comment]
I haven't gotten far enough to need ``agent-install.sh``, but thanks for mentioning it. The do-nothing option is still a great idea for ``deploy-mgmt-hub.sh`` although that's for another issue at another time...
