### ISSUE TITLE
Research and document CI tools

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/devops#43]
Investigate and research open source CI technologies to migrate the Open-Horizon projects to from using Travis-CI. 
### Possible Options
1. LF-Edge Jenkins & Jenkins Job Builder Plugin
2. GitHub Actions
3. CircleCI - Research to see if there is a free option for Open Source projects

### Output:
* Fork and create a branch in the `open-horizon/devops` repo
* Create a Pros/Cons for each one in MarkDown format in a new folder called `documentation` 
    * will need to create criteria list to judge the tools on

**Comment by Al-tekreeti** [comment]
Can you assign it to me?

**Comment by Al-tekreeti** [comment]
So far, a readme file is created in `devops/documentation` in which the main features, usage limits, VM specs, and incurred costs of the GitHub actions, Circle-CI, and LF Edge system are summarized. Then, the development life-cycle of the pipeline using GitHub actions and the LF Edge system is schematically demonstrated. Lastly, the average execution time delay for a pipeline that implements the e2e-dev-test using GitHub actions is reported.

**Comment by bencourliss** [comment]
This work is completed.
