### ISSUE TITLE
Implement e2edev CI tooling for Anax

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/devops#45]
Based on chosen CI build option to replace Travis-CI, create a build pipeline that can compile Anax and run the e2edev tests
Should integrate with GitHub Pull Requests. So anytime a PR is created for Anax, it should trigger this build pipeline and serve as a gate to a PR merge. Once this is working in your own fork, you will need the help of an administrator to change the Anax GitHub repo settings.

**Comment by Al-tekreeti** [comment]
Can you assign it to me?

**Comment by Al-tekreeti** [comment]
I think this is done using GitHub actions.

**Comment by bencourliss** [comment]
This work is completed.
