### ISSUE TITLE
All-in-1 should not run brew as root on macOS

### ISSUE THREAD

**Issue by girishkumarbk** [open-horizon/devops#48]
root# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash

----------- Verifying input and the host OS...
Management hub services will listen on 127.0.0.1
Installing prerequisites using brew, this could take a minute...
Error running brew install jq gettext: Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

MacOS: Big Sur 11.0.1

**Comment by bmpotter** [comment]
Fixed in https://github.com/open-horizon/devops/pull/52

**Comment by bmpotter** [comment]
Closing this issue because i haven't heard from @girishkumarbk about testing it in 4 months.
