### ISSUE TITLE
Build Anax Docker images and upload to Dockerhub 

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/devops#57]
When a PR is created, a GitHub Action runs the e2edev test against the new code. Once this is successful, the code should be merged in and a new GitHub Action should be kicked off that builds Anax and creates the Docker images. These images should be uploaded into Dockerhub. 

Output of this Issue should be to create the second GH Action that builds and uploads the docker images. You can use your own fork for development and upload into your own Dockerhub private repo for testing. Once the code is finished and working, it should be changed to use the OpenHorizon org's Dockerhub repo.

**Comment by Al-tekreeti** [comment]
Okay, can you assign it to me?

**Comment by Al-tekreeti** [comment]
The second workflow is created that would kick off when the e2edev test is successful.  It would build the required docker images for amd64 architecture and upload them to the docker hub.

**Comment by bencourliss** [comment]
This work has been completed.
