### ISSUE TITLE
AGBOT_ID is not honored in deploy-mgmt-hub.sh

### ISSUE THREAD

**Issue by linggao** [open-horizon/devops#62]
Setting the environment variable AGBOT_ID to something other than `agbot` does not work. The agbot id in the exchange is always 'agbot'

[These lines](https://github.com/open-horizon/devops/blob/master/mgmt-hub/deploy-mgmt-hub.sh#L756-L767) need to use the variable `$AGBOT_ID` instead of hardcoded `agbot`

**Comment by bmpotter** [comment]
@linggao I'm assigning this issue to you so you can verify it. It was fixed back in april with [devops PR 63](https://github.com/open-horizon/devops/pull/63) .
