### ISSUE TITLE
All-in-1 improvements for e2edev

### ISSUE THREAD

**Issue by linggao** [open-horizon/devops#64]
There are a few improvements needed for all-in-1 to be used by e2edev:

- [x] Image pull: Always pull when the image tag is `latest` or `testing`.  For other tags, try to pull, but do not report error if the image exists locally, but does not exist in the remote repo. This way e2edev can use the locally built image.
- [x] Add a second agbot when env variable `START_SECOND_AGBOT` is set to `true`.
- [x] Add `-c <config-file>` to be able to pass in a set env vars
- [x] Add `HZN_AGBOT_URL` and `HZN_SDO_SVC_URL` to `/etc/default/horizon` and `agent-install.cfg`
- [x] Test/fix listening on 0.0.0.0 with external edge node
- [x] Change **Adding More Edge Nodes** section to use https://github.com/open-horizon/anax/releases/latest/download/agent-install.sh when the necessary version of `agent-install.sh` is released to https://github.com/open-horizon/anax/releases
- [x] Expose the agbot secure APIs (even before adding TLS support). For example:
```
    "SecureAPIListenHost": "0.0.0.0",
    "SecureAPIListenPort": "8083",
```

**Comment by bmpotter** [comment]
Tested by e2edev
