### ISSUE TITLE
Fix "pausing" the services section

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/devops#7]
In the following section: https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md#-pausing-the-services you show how to stop the services.  The instructions assume that the person has a local copy of the script.  However, the one-liner that we used to install and run the services did not save a local copy.  You may fix that by adding the following to the instructions:

Save a local executable copy of the script by running:

``` shell
curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh > deploy-mgmt-hub.sh
chmod a+x deploy-mgmt-hub.sh
```

**Comment by bmpotter** [comment]
https://github.com/open-horizon/devops/pull/8 is ready for review

**Comment by joewxboy** [comment]
Fixed, closing
