### ISSUE TITLE
deploy-mgmt-hub.sh should check /tmp/horizon before using it

### ISSUE THREAD

**Issue by linggao** [open-horizon/devops#70]
User got the following error when running deploy-mgmt-hub.sh
````
----------- Downloading template files...
/tmp/deploy-mgmt-hub.sh: line 404: /tmp/horizon/curlExchangeErrors: Not a directory
Error: http code 200 from: /tmp/horizon/curlExchangeErrors
All-in-one management hub deployment: Failed deploy.
Makefile:438: recipe for target 'run-mgmthub' failed
make: *** [run-mgmthub] Error 1
````
This is because that there is a file called `/tmp/horizon` exists. `deploy-mgmt-hub.sh` command should tolerate it and delete it. Another suggestion is that it uses a non-general name like `/tmp/horizon-mgmt-hub` instead of `/tmp/horizon` to reduce the chances of conflicts.

**Comment by bmpotter** [comment]
Changing to use `/tmp/horizon-all-in-1` instead.

**Comment by bmpotter** [comment]
Been running this way for 3 months with no problems reported, so closing it.
