### ISSUE TITLE
Add agbot URL to the agent configuration

### ISSUE THREAD

**Issue by linggao** [open-horizon/devops#71]
- [x] `HZN_AGBOT_URL` in `/etc/default/horizon` (completed several weeks ago in a separate issue)

The related Anax issue is https://github.com/open-horizon/anax/issues/2465

**Comment by bmpotter** [comment]
@linggao Does `AdbotURL` need to be added to the agent config file or the agbot config file? If agent, isn't adding `HZN_AGBOT_URL` to `/etc/default/horizon` good enough?
