### ISSUE TITLE
Encounter FileNotFoundError when executing ./deploy-mgmt-hub.sh

### ISSUE THREAD

**Issue by oliverchan** [open-horizon/devops#82]
Hi

Hit into following error when executed either ./deploy-mgmt-hub.sh or curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
`root@hub:/home/oliver# ./deploy-mgmt-hub.sh
Management hub services will listen on http://127.0.0.1
Updating apt-get package index...
Installing prerequisites, this could take a minute...
----------- Downloading template files...
Substituting environment variables into template files...
----------- Downloading/starting Horizon management hub services...
Downloading management hub docker images...
Pulling openhorizon/amd64_agbot:latest ...
Pulling openhorizon/amd64_exchange-api:latest ...
Pulling openhorizon/amd64_cloud-sync-service:latest ...
Pulling postgres:latest ...
Pulling mongo:latest ...
Pulling openhorizon/sdo-owner-services:latest ...
Starting management hub containers...
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[6747] Failed to execute script docker-compose
Error: exit code 255 from: starting docker-compose services
root@hub:/home/oliver#`

**Comment by bmpotter** [comment]
@oliverchan It looks like you have the python version of `docker-compose` installed on your system, instead of the more common golang version. The person who opened [issue 76](https://github.com/open-horizon/devops/issues/76) had the same error. But their situation was caused by `deploy-mgmt-hub.sh` not defaulting to the correct version of `docker-compose` in some circumstances. But that was fixed a month ago.

The only environment that we've tested the python version of `docker-compose` in is ppc64. All other environments should be using the golang version. Please look at your path and figure out where `docker-compose` is coming from and who installed it.

**Comment by oliverchan** [comment]
@bmpotter , thanks for the response. Taken a look of [isse 76](https://github.com/open-horizon/devops/issues/76)
I believe I faced exactly what the person faced as well. My issue was faced by executing the same command `curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash` on a newly setup VM, and I don't think I have the python version of docker-compose installed on the VM.

Regards
Oliver

**Comment by oliverchan** [comment]
@bmpotter .  I believe something was changed. I'm receiving a different error. Will you be able advice what I can do to overcome the below error?

**Comment by oliverchan** [comment]
@bmpotter
Suspect something to do with css-api and mongo db. Here's the trace from docker ps and docker log css-api

`root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS                                PORTS
                                   NAMES
9429f753ced3   openhorizon/amd64_agbot:latest                "/bin/sh -c /usr/hor…"   3 minutes ago   Up 3 minutes (healthy)                127.0.0.1:3110->8080/tcp, 127.0.0.1:3111->8083/tcp                             agbot
cc5ab604e795   openhorizon/sdo-owner-services:latest         "/bin/sh -c $WORKDIR…"   3 minutes ago   Up 3 minutes (healthy)                127.0.0.1:8040->8040/tcp, 127.0.0.1:8042->8042/tcp, 127.0.0.1:9008->9008/tcp   sdo-owner-services
313002718baa   openhorizon/amd64_cloud-sync-service:latest   "/usr/edge-sync-serv…"   3 minutes ago   Up 3 minutes (unhealthy)              127.0.0.1:9443->8080/tcp
                                   css-api
57af38a61a33   openhorizon/amd64_exchange-api:latest         "/bin/sh -c '/usr/bi…"   3 minutes ago   Up 3 minutes (healthy)                8083/tcp, 127.0.0.1:3090->8080/tcp
                                   exchange-api
9ee61958532b   mongo:latest                                  "docker-entrypoint.s…"   3 minutes ago   Restarting (132) About a minute ago
                                   mongo
7248ee7b6556   postgres:latest                               "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)                5432/tcp
                                   postgres
root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# docker ps | grep css-api
313002718baa   openhorizon/amd64_cloud-sync-service:latest   "/usr/edge-sync-serv…"   3 minutes ago   Up 3 minutes (unhealthy)          127.0.0.1:9443->8080/tcp
                               css-api
root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# docker logs css-api
* CSS: 2021/07/14 15:54:21 Loaded configuration:
  NodeType  CSS
  DestinationType  Cloud
  DestinationID  Cloud
  OrgID
  ListeningType  unsecure
  ListeningAddress
  SecureListeningPort  8080
  UnsecureListeningPort  8080
  ServerCertificate  <...>
  ServerKey  <...>
  CSSOnWIoTP  false
  UsingEdgeConnector  false
  LeadershipTimeout  30
  AuthenticationHandler  dummy
  CommunicationProtocol  http
  MQTTClientID
  MQTTUserName
  MQTTPassword
  MQTTUseSSL  true
  MQTTCACertificate  <...>
  MQTTSSLCert
  MQTTSSLKey
  MQTTAllowInvalidCertificates  false
  MQTTBrokerConnectTimeout  300
  MQTTParallelMode
  PersistenceRootPath  /var/edge-sync-service/persist/
  BrokerAddress
  BrokerPort  0
  HTTPPollingInterval  10
  HTTPCSSHost
  HTTPCSSPort  0
  HTTPCSSUseSSL  false
  HTTPCSSCACertificate
  LogLevel  INFO
  LogRootPath  /var/edge-sync-service/log
  LogTraceDestination  stdout
  LogFileName  sync-service
  TraceLevel  INFO
  TraceRootPath  /var/edge-sync-service/trace
  TraceFileName  sync-service
  LogTraceFileSizeKB  20000
  MaxCompressedlLogTraceFilesNumber  50
  LogTraceMaintenanceInterval  60
  ResendInterval  5
  ESSPingInterval  1
  RemoveESSRegistrationTime  30
  MaxDataChunkSize  122880
  MaxInflightChunks  1
  MongoAddressCsv  mongo:27017
  MongoAuthDbName  admin
  MongoDbName  d_edge
  MongoUsername
  MongoPassword
  MongoUseSSL  false
  MongoCACertificate
  MongoAllowInvalidCertificates  false
  MongoSessionCacheSize  1
  DatabaseConnectTimeout  300
  StorageMaintenanceInterval  30
  ObjectActivationInterval  30
  StorageProvider  mongo
  ESSConsumedObjectsKept  1000
  MessagingGroupCacheExpiration  60
  ShutdownQuiesceTime  60
  ObjectsDataPath
CSS: 2021/07/14 15:54:22 INFO: Horizon Authenticator starting with exchange authenticated identity
* CSS: 2021/07/14 15:54:22 INFO: Connecting to mongo...
* CSS: 2021/07/14 15:54:42 ERROR: Failed to dial mgo. Error: no reachable servers
* CSS: 2021/07/14 15:54:42 ERROR: Retrying to connect to mongo

**Comment by ilamprinos** [comment]
> @bmpotter Suspect something to do with css-api and mongo db. Here's the trace from docker ps and docker log css-api
> 
> `root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# **docker ps** CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 9429f753ced3 openhorizon/amd64_agbot:latest "/bin/sh -c /usr/hor…" 3 minutes ago Up 3 minutes (healthy) 127.0.0.1:3110->8080/tcp, 127.0.0.1:3111->8083/tcp agbot cc5ab604e795 openhorizon/sdo-owner-services:latest "/bin/sh -c $WORKDIR…" 3 minutes ago Up 3 minutes (healthy) 127.0.0.1:8040->8040/tcp, 127.0.0.1:8042->8042/tcp, 127.0.0.1:9008->9008/tcp sdo-owner-services 313002718baa openhorizon/amd64_cloud-sync-service:latest "/usr/edge-sync-serv…" 3 minutes ago Up 3 minutes (unhealthy) 127.0.0.1:9443->8080/tcp css-api 57af38a61a33 openhorizon/amd64_exchange-api:latest "/bin/sh -c '/usr/bi…" 3 minutes ago Up 3 minutes (healthy) 8083/tcp, 127.0.0.1:3090->8080/tcp exchange-api 9ee61958532b mongo:latest "docker-entrypoint.s…" 3 minutes ago Restarting (132) About a minute ago mongo 7248ee7b6556 postgres:latest "docker-entrypoint.s…" 3 minutes ago Up 3 minutes (healthy) 5432/tcp postgres root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# docker ps | grep css-api 313002718baa openhorizon/amd64_cloud-sync-service:latest "/usr/edge-sync-serv…" 3 minutes ago Up 3 minutes (unhealthy) 127.0.0.1:9443->8080/tcp css-api root@oliver-VirtualBox:/home/oliver/devops/mgmt-hub# **docker logs css-api**
> 
> * CSS: 2021/07/14 15:54:21 Loaded configuration:
>   NodeType  CSS
>   DestinationType  Cloud
>   DestinationID  Cloud
>   OrgID
>   ListeningType  unsecure
>   ListeningAddress
>   SecureListeningPort  8080
>   UnsecureListeningPort  8080
>   ServerCertificate  <...>
>   ServerKey  <...>
>   CSSOnWIoTP  false
>   UsingEdgeConnector  false
>   LeadershipTimeout  30
>   AuthenticationHandler  dummy
>   CommunicationProtocol  http
>   MQTTClientID
>   MQTTUserName
>   MQTTPassword
>   MQTTUseSSL  true
>   MQTTCACertificate  <...>
>   MQTTSSLCert
>   MQTTSSLKey
>   MQTTAllowInvalidCertificates  false
>   MQTTBrokerConnectTimeout  300
>   MQTTParallelMode
>   PersistenceRootPath  /var/edge-sync-service/persist/
>   BrokerAddress
>   BrokerPort  0
>   HTTPPollingInterval  10
>   HTTPCSSHost
>   HTTPCSSPort  0
>   HTTPCSSUseSSL  false
>   HTTPCSSCACertificate
>   LogLevel  INFO
>   LogRootPath  /var/edge-sync-service/log
>   LogTraceDestination  stdout
>   LogFileName  sync-service
>   TraceLevel  INFO
>   TraceRootPath  /var/edge-sync-service/trace
>   TraceFileName  sync-service
>   LogTraceFileSizeKB  20000
>   MaxCompressedlLogTraceFilesNumber  50
>   LogTraceMaintenanceInterval  60
>   ResendInterval  5
>   ESSPingInterval  1
>   RemoveESSRegistrationTime  30
>   MaxDataChunkSize  122880
>   MaxInflightChunks  1
>   MongoAddressCsv  mongo:27017
>   MongoAuthDbName  admin
>   MongoDbName  d_edge
>   MongoUsername
>   MongoPassword
>   MongoUseSSL  false
>   MongoCACertificate
>   MongoAllowInvalidCertificates  false
>   MongoSessionCacheSize  1
>   DatabaseConnectTimeout  300
>   StorageMaintenanceInterval  30
>   ObjectActivationInterval  30
>   StorageProvider  mongo
>   ESSConsumedObjectsKept  1000
>   MessagingGroupCacheExpiration  60
>   ShutdownQuiesceTime  60
>   ObjectsDataPath
>   CSS: 2021/07/14 15:54:22 INFO: Horizon Authenticator starting with exchange authenticated identity
> * CSS: 2021/07/14 15:54:22 INFO: Connecting to mongo...
> * CSS: 2021/07/14 15:54:42 ERROR: Failed to dial mgo. Error: no reachable servers
> * CSS: 2021/07/14 15:54:42 ERROR: Retrying to connect to mongo

Does anyone have an answer in this I have the exact same problem with the exact same logs.

**Comment by ilamprinos** [comment]
https://github.com/open-horizon/devops/issues/82#issuecomment-879965016
I am facing the exact same thing. Does anyone have any solution? @oliverchan did you solve it?

**Comment by ravinata** [comment]
same error here. I tried like 5 times in brand new Ubuntu VMs both 18.x and 20.x.  I also ensured, I did a apt update, apt upgrade this time...  nothing works and same error.   Jesus. I am tired.  Another point is, we cant re-run this because we get the vault error (Hashicorp vault)...  so, installation cannot be re-run easily or deleted / cleaned-up easily.

**Comment by ilamprinos** [comment]
@ravinata Check issue #137
