### ISSUE TITLE
Problem with installation Horizon Management Hub

### ISSUE THREAD

**Issue by TParashchuk** [open-horizon/devops#94]
Hi. I am trying to setup all-in-one management hub in a Ubuntu 18.04.4 and 20.04.3 LTS (Virtual box). My issues with command for run deploy-mgmt-hub.sh, it doesn't working correctly, how I see docker containers was created and started, but edge node wasn't created. 

The logs Ubuntu 20.04.3 LTS:

root@ubuntuoh:~ curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
------- Checking input and initializing...
Management hub services will listen on http://127.0.0.1
Updating apt-get package index...
Installing prerequisites, this could take a minute...
Docker is required, installing it...
OK
Hit:1 http://ua.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://ua.archive.ubuntu.com/ubuntu focal-security InRelease
Get:5 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Get:6 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [11.6 kB]
Fetched 69.3 kB in 1s (109 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  docker-ce-rootless-extras docker-scan-plugin pigz slirp4netns
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite
The following NEW packages will be installed:
  containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras docker-scan-plugin pigz slirp4netns
0 upgraded, 7 newly installed, 0 to remove and 28 not upgraded.
Need to get 95.6 MB of archives.
After this operation, 403 MB of additional disk space will be used.
Get:1 http://ua.archive.ubuntu.com/ubuntu focal/universe amd64 pigz amd64 2.4-1 [57.4 kB]
Get:2 http://ua.archive.ubuntu.com/ubuntu focal/universe amd64 slirp4netns amd64 0.4.3-1 [74.3 kB]
Get:3 https://download.docker.com/linux/ubuntu focal/stable amd64 containerd.io amd64 1.4.11-1 [23.7 MB]
Get:4 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-ce-cli amd64 5:20.10.9~3-0~ubuntu-focal [38.8 MB]
Get:5 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-ce amd64 5:20.10.9~3-0~ubuntu-focal [21.2 MB]
Get:6 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-ce-rootless-extras amd64 5:20.10.9~3-0~ubuntu-focal [7,914 kB]
Get:7 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-scan-plugin amd64 0.8.0~ubuntu-focal [3,889 kB]Fetched 95.6 MB in 5s (21.1 MB/s)
Selecting previously unselected package pigz.
(Reading database ... 71545 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Selecting previously unselected package containerd.io.
Preparing to unpack .../1-containerd.io_1.4.11-1_amd64.deb ...
Unpacking containerd.io (1.4.11-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../2-docker-ce-cli_5%3a20.10.9~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-cli (5:20.10.9~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../3-docker-ce_5%3a20.10.9~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce (5:20.10.9~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce-rootless-extras.
Preparing to unpack .../4-docker-ce-rootless-extras_5%3a20.10.9~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-rootless-extras (5:20.10.9~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-scan-plugin.
Preparing to unpack .../5-docker-scan-plugin_0.8.0~ubuntu-focal_amd64.deb ...
Unpacking docker-scan-plugin (0.8.0~ubuntu-focal) ...
Selecting previously unselected package slirp4netns.
Preparing to unpack .../6-slirp4netns_0.4.3-1_amd64.deb ...
Unpacking slirp4netns (0.4.3-1) ...
Setting up slirp4netns (0.4.3-1) ...
Setting up docker-scan-plugin (0.8.0~ubuntu-focal) ...
Setting up containerd.io (1.4.11-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.Setting up docker-ce-cli (5:20.10.9~3-0~ubuntu-focal) ...
Setting up pigz (2.4-1) ...
Setting up docker-ce-rootless-extras (5:20.10.9~3-0~ubuntu-focal) ...
Setting up docker-ce (5:20.10.9~3-0~ubuntu-focal) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.11) ...
docker-compose is not installed or not at least version 1.21.0, installing/upgrading it...
######################################################################## 100.0%##O=#  #                                 ######################################################################## 100.0%#-#O=#  #                                ######################################################################## 100.0%
------- Downloading template files...
Substituting environment variables into template files...
------- Downloading/starting Horizon management hub services...
Downloading management hub docker images...
Pulling openhorizon/amd64_agbot:latest ...
Pulling openhorizon/amd64_exchange-api:latest ...
Pulling openhorizon/amd64_cloud-sync-service:latest ...
Pulling postgres:latest ...
Pulling mongo:latest ...
Pulling openhorizon/sdo-owner-services:latest ...
Pulling openhorizon/amd64_vault:latest ...
Starting management hub containers...
[+] Running 13/13
 ⠿ Network hzn_horizonnet        Created                                                                           0.3s
 ⠿ Volume "hzn_agbotmsgkeyvol"   Created                                                                           0.0s
 ⠿ Volume "hzn_postgresvol"      Created                                                                           0.0s
 ⠿ Volume "hzn_mongovol"         Created                                                                           0.0s
 ⠿ Volume "hzn_ocsdb"            Created                                                                           0.0s
 ⠿ Volume "hzn_vaultvol"         Created                                                                           0.0s
 ⠿ Container mongo               Started                                                                           6.0s
 ⠿ Container postgres            Started                                                                           6.1s
 ⠿ Container exchange-api        Started                                                                           4.5s
 ⠿ Container css-api             Started                                                                           9.2s
 ⠿ Container sdo-owner-services  Started                                                                           8.3s
 ⠿ Container vault               Started                                                                           9.1s
 ⠿ Container agbot               Started                                                                          11.9s
Waiting for the exchange.............
------- Creating the user org, and the admin user in both orgs...
Creating exchange hub admin user, and the admin user and agbot in the system org...
------- Creating a Vault instance and preforming all setup and configuration operations ...
Checking Vault service status, initialization, and seal...
A Vault instance has not been initialized. Initializing...
Vault instance is sealed. Unsealing...
Creating KV ver.2 secrets engine openhorizon...
Registering auth plugin openhorizon-exchange to Vault instance...
Generating SHA256 hash of openhorizon-exchange plugin...
Enabling auth method openhorizon-exchange for secrets engine openhorizon...
Configuring auth method openhorizon-exchange for use with the Exchange...
Success! Data written to: auth/openhorizon/config
root@ubuntuoh:~# hzn node list
hzn: command not found
root@ubuntuoh:~# docker ps -a
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS                            PORTS                                                                          NAMES
a745bfc14e96   openhorizon/amd64_agbot:latest                "/bin/sh -c /usr/hor…"   18 minutes ago   Restarting (2) 47 seconds ago                                                                                    agbot
0da9eb60d590   openhorizon/amd64_cloud-sync-service:latest   "/usr/edge-sync-serv…"   18 minutes ago   Up 6 minutes (unhealthy)          127.0.0.1:9443->8080/tcp                                                       css-api
f3777e743bbf   openhorizon/sdo-owner-services:latest         "/bin/sh -c $WORKDIR…"   18 minutes ago   Up 18 minutes (healthy)           127.0.0.1:8040->8040/tcp, 127.0.0.1:8042->8042/tcp, 127.0.0.1:9008->9008/tcp   sdo-owner-services
6d38e46f0e99   openhorizon/amd64_vault:latest                "entrypoint.sh server"   18 minutes ago   Up 18 minutes (healthy)           127.0.0.1:8200->8200/tcp                                                       vault
3b8b4ef7533d   openhorizon/amd64_exchange-api:latest         "/bin/sh -c '/usr/bi…"   18 minutes ago   Up 18 minutes (healthy)           8083/tcp, 127.0.0.1:3090->8080/tcp                                             exchange-api
37a5230b6522   mongo:latest                                  "docker-entrypoint.s…"   18 minutes ago   Restarting (132) 52 seconds ago                                                                                  mongo
838a0541cf5a   postgres:latest                               "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (healthy)           5432/tcp                                                                       postgres
root@ubuntuoh:~

**Comment by bmpotter** [comment]
@naphelps so probably `docker-compose exec ...` is reading the stdin? Why did you use `docker-compose exec` instead of `docker exec`? I'm wondering if using the latter and **not** specifying `-i` would prevent it from reading stdin.
